apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hack-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/jenkins"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/jenkins)$ http://$best_http_host$1/ permanent;
spec:
  rules:
  - http:
      paths:
      - path: "/jenkins"
        backend:
          serviceName: jeknins-service
          servicePort: 8000
