apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hack-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: "/flask"
        backend:
          serviceName: flask-service
          servicePort: 8000
