apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: default
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    name: master
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: agent
    port: 50000
    targetPort: 50000
  type: LoadBalancer
