apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hack-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: "/(.*)"
        backend:
          serviceName: flask-service
          servicePort: 8080
